'use client'
import './index.css'
// import Layout from '@/app/layouts'
// import ReduxProvider from '../redux/provider'
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Provider } from 'react-redux'
import store from '../redux/store'
import { Header } from '@/components/Header'
import SubFooter from '@/components/home/SubFooter'
import Footer from '@/components/home/Footer'
import CallToAction from '@/components/home/CallToAction'
import { usePathname } from 'next/navigation'
// export const metadata = {
//   title: "Urban",
//   description: "Generated by create next app",
// };

const shouldRenderComponents = (pathname: string): boolean => {
	return !pathname.startsWith('/dashboard')
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const pathname = usePathname()
	const isDashboardPage = shouldRenderComponents(pathname)

	return (
		<html lang='en' className={`font-sans`}>
			<Provider store={store}>
				{/* <Layout> */}

				<body>
					{isDashboardPage && <Header />}
					{children}
					{isDashboardPage && <CallToAction />}
					{isDashboardPage && <SubFooter />}
					{isDashboardPage && <Footer />}
				</body>
				<ProgressBar
					height='4px'
					color='#1F9FDA'
					options={{ showSpinner: true }}
					shallowRouting
				/>
				<Analytics />
				<SpeedInsights />
				{/* </Layout> */}
			</Provider>
		</html>
	)
}
