import React from 'react'
import Footer from '../frontend/src/components/Footer'
import { Outlet } from 'react-router-dom'
import { Header } from '../frontend/src/components/Header'

export const metadata = {
	title: 'Auth',
	description: 'Generated by create next app',
}

export default function AuthLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div>
			<Header />
			<Outlet />
			<Footer />
			{/* {children} */}
		</div>
	)
}
